services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AdamWojs\IbexaFormBuilderRecaptcha\FormBuilder\Field\Mapper\ReCaptchaMapper:
        arguments:
            $fieldIdentifier: 'recaptcha'
            $formType: 'AdamWojs\IbexaFormBuilderRecaptcha\Form\Type\ReCaptchaFieldType'
        tags:
            - { name: ibexa.form_builder.field.mapper }
